stages:
  - build
  - server

build:
  stage: build
  script: 
    - apt-get update && apt-get install -y curl
    - git config --global user.name "Starlis CI"
    - git config --global user.email "noreply@starlis.com"
    - git submodule update --init --recursive
    - ./ecraft up
    - ./ecraft patch
    - mvn clean install -U -B
    - cp server/target/empirecraft.jar /test-server/minecraft_server.jar

server:
  stage: server
  script:
    - cd /test-server
    - echo "Failed to load plugin" > TEST_RESULTS
    - java  -DIReallyKnowWhatIAmDoingISwear=1 -XX:+UseG1GC -DCISERVER=1 -Xmx1G -jar minecraft_server.jar
    - test ! -s TEST_RESULTS || (cat TEST_RESULTS ; echo "" ; exit 1)
